# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jaehyeok Han
title: Ph.D student
email: one01h@korea.ac.kr
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: one01h
github_username:  JaehyeokHan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: jaehye0k
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: jaehyeok-han-67013a111
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll
# orcid_username: 0000-0001-5724-0775

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-EBNBGEBGNZ"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I received B.S. in Natural Science College of Mathematics from University of Seoul (UOS) and M.E. degrees in School of Cybersecurity from Korea University in 2011 and 2016, respectively. Since March 2016, I have studied as a Ph.D. student in with the School of Cybersecurity at Korea University, and have worked as a researcher of Digital Forensic Research Center (DRFC) at Institute of Cyber Security & Privacy (ICSP).
  
  My research interests include *digital forensics*, *information security*, and *cryptography*.

  - [School of Cybersecurity](https://gss.korea.edu/), [Korea University](http://www.korea.edu/)
  - [Digital Forensic Research Center (DFRC)](http://forensic.korea.ac.kr/) [*[RETR](https://sites.google.com/a/forensic.or.kr/main/)*] at Institute of Cyber Security & Privacy (ICSP)
  
content:
  - title: Project # Title for the section
    layout: list # Type of content section (list/text/text2)
    content:
      - layout: left
        title: CARPE Forensics
        link: http://carpeforensics.org/
        link_text: http://carpeforensics.org/
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/dfrc-korea/carpe
        quote: >
          Comprehensive Analysis and Research Platform for digital Evidence
        description: | # this will include new lines to allow paragraphs
          CARPE is Digital Forensic Integration Framework. Because this framework is open source, it can be used to build digital forensic infrastructure through ecosystem building. In addition, verification of the code can evolve to a reliable level of code, and development can be carried out with user requirements. For the digital forensic analyst, this technology enables efficient work in the analysis process through automated modules. In the developer's view, it can be used to develop not only digital forensic research but also own tool by utilizing open source. Recently, the processing technology for large-capacity data is developed for each module, and not only related data analysis but also keyword search, string extraction, and file fragment recombination are provided.
  - title: Education
    layout: text2
    content:
      - layout: left
        title: Ph.D student
        sub_title: Mar. 2016 - Present
        description: | # this will include new lines to allow paragraphs
          School of Cybersecurity, Korea University, Seoul, South Korea
#         Dissertation:

      - layout: left
        title: Master of Engineering (M.E.) - Information security (Digital forensics)
        sub_title: Mar. 2014 - Feb. 2016
        description: | # this will include new lines to allow paragraphs
          <p>Graduate School of information Security, South Korea. Advised by <A href = "https://scs.korea.ac.kr/ime/professor/honor.do?mode=view&articleNo=36554&article.offset=0&articleLimit=30" target = "top">Sangjin Lee</A></p>
          <p>Thesis: <i>Analysis of the HIKVISION DVR filesystem</i></p>

      - layout: left
        title: Bachelor of Science (B.S) - Mathematics
        sub_title: Mar. 2007 - Feb. 2011
        description: | # this will include new lines to allow paragraphs
          <p>University of Seoul (UOS), Seoul, South Korea. Advised by <A href = "https://www.uos.ac.kr/en/professor/view.do?proseq=14&code=20031&pageIndex=1&epTicket=LOG" target = "top">Jaechul Sung</A></p>
    
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Project
#       sub_title: Job title
#       caption: Date Range (eg. November 2016 - present)
#       link: Link to company (optional)
        quote: >
          TBC
        description: | # this will include new lines to allow paragraphs
          Writing

      - layout: left
        title: Case
        quote: >
          TBC
        description: | # this will include new lines to allow paragraphs
          Writing

      - layout: left
        title: Lecture
        quote: >
          TBC
        description: | # this will include new lines to allow paragraphs
          <p>(2020F, 2021S) Ewha Univ. &#35;38497 - Digital forensics</p>
          <p>(2020S, 2021S) Dongguk Univ. &#35;PAS4022 - Mobile forensics</p>
          <p>(2018W, 2019W, 2020W) Korea Univ. &#35;IMS4001 - Practical affarirs in digital forensic</p>
          <p>(2017F, 2018F, 2019F, 2020F) Korea Univ. &#35;ITCS403 - Mobile forensics</p>

      - layout: left
        title: Media
        quote: >
          TBC
        description: | # this will include new lines to allow paragraphs
          Writing
          
  - title: Publication
    layout: list
    content: # Citation style: APA (American Psychological Association)
      - layout: left
        title: Journal
#       sub_title: Job title
#       caption: Date Range (eg. November 2016 - present)
#       link: Link to company (optional)
#       quote: >
#         Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
         <p>[3] 5W1H-based Expression for the Effective Sharing of Information in Digital Forensic Investigations<br>&nbsp;&nbsp;Han, J., Kim, J., & Lee, S. (2020). arXiv preprint arXiv:2010.15711.</p>
         <p>[2] Forensic analysis of the Windows telemetry for diagnostics<br>&nbsp;&nbsp;Han, J., Park, J., Chung, H., & Lee, S. (2020). arXiv preprint arXiv:2002.12506.</p>
         <p>[1] Threat Assessment for Android Environment with Connectivity to IoT Devices from the Perspective of Situational Awareness<br>&nbsp;&nbsp;Park, M., Han, J., Oh, H., & Lee, K. (2019). Wireless Communications and Mobile Computing, 2019.</p>
          
      - layout: left
        title: Conforence
#       quote: >
#         Short description of the company (optional)        
        description: | # this will include new lines to allow paragraphs
          <p>[11] <b>Jaehyeok Han</b>, Hyunji Chung, and Sangjin Lee, "I can login without your password: Data acquisition from web based server using user credential attack" DFRWS APAC 2021, 2021.01.</p>
          <p>[10] <b>Jaehyeok Han</b>, and Sangjin Lee, "A Study on the Processing of Timestamps in Creating Multimedia Files on Mobile devices" The 12th International Conference Computer Science and its Applications (CSA2020), 2020.12.</p>
          <p>[9] Sunghee Lim, <b>Jaehyeok Han</b>, and Sangjin Lee, "Replay attack to DRM in music streaming service on Android" The 12th International Conference on Internet (ICONI) 2020, 2020.12.</p>
          <p>[8] Park, M., Seo, J., Han, J., Oh, H., & Lee, K. (2018). Situational Awareness Framework for Threat Intelligence Measurement of Android Malware. J. Wirel. Mob. Networks Ubiquitous Comput. Dependable Appl., 9(3), 25-38.</p>
          <p>[7] Mookyu Park, Junwoo Seo, <b>Jaehyeok Han</b>, Haengrok Oh, and Kyungho Lee,"Situational Awareness for Hybrid Warfare: Risk Measurement Between Cyber Warfare and Nuclear Warfare", 17th European Conference on Cyber Warfare and Security(ECCWS 2018), 2018.06.</p>
          <p>[6] Mookyu Park, <b>Jaehyeok Han</b>, Moosung Park, and Kyungho Lee, "Situational Awareness for Cyber Threat Intelligence Using LSTM Based RNN", 2018 International Conference on Platform Technology and Service(PlatCon-18), 2018.01.</p>
          <p>[5] Mookyu Park, <b>Jaehyeok Han</b>, Moosung Park, and Kyungho Lee, "What is Next September. 11? Risk Measurement of Hybrid Warfare about Boeing 787 Dreamliner using FAIR Model", The 9th International Conference on Internet(ICONI 2017), 2017.12.</p>
          <p>[4] <b>Jaehyeok Han</b>, Mookyu Park, Moosung Park, Kyungho Lee, and Sangjin Lee, "Analysis model for Digital Forensic Intelligence in case of the Confidential Leaks", The 9th International Conference on Internet(ICONI 2017), 2017.12.</p>
          <p>[3] Park, M., Han, J., Seo, J., Oh, H., & Lee, K. (2017, October). FAIR-Based Cyber Influence Damage Assessment for Exploit in Mobile Device. In International Symposium on Mobile Internet Security (pp. 51-64). Springer, Singapore.</p>
          <p>[2] Han, J., & Lee, S. (2016). A practical approach to analyze smartphone backup data as a digital evidence. DFRWS USA, 2016.</p>
          <p>[1] Han, J., Jeong, D., & Lee, S. (2015, October). Analysis of the HIKVISION DVR file system. In International Conference on Digital Forensics and Cyber Crime (pp. 189-199). Springer, Cham.</p>
          
      - layout: left
        title: Domestics (in Korea)
        description: | # this will include new lines to allow paragraphs
          <p>[j14] Yoon, S., Han, J., Kwon, H., & Lee, S. (2020). Improvements of Searching and Seizing Steganographic Evidence. Korean Lawyers Association Journal, 69(6), 184-225.</p>
          <p>[j13] Kim, D., Han, J., & Lee, S. (2020). A study on forensic analysis for Windows search utility Everything. Journal of Digital Forensics, 14(3), 279-289.</p>
          <p>[c9] 김동현, 한재혁, 이상진, "검색 유틸리티 Everything에 대한 포렌식 분석 및 활용 기법 연구", 한국디지털포렌식학회 하계학술대회(WDFS-2020s), 2020.07.</p>
          <p>[j12] Han, J., Yoon, Y., Hur, G., Lee, J., Choi, J., Hong, S., & Lee, S. (2019). Secure File Transfer Method and Forensic Readiness by converting file format in Network Segmentation Environment. Journal of the Korea Institute of Information Security & Cryptology, 29(4), 859-866.</p>
          <p>[c8] 엄민지, 한재혁, 이상진, "윈도우에서 ZIP 파일 생성 프로그램 추정 기법", 한국정보보호학회 하계학술대회(CISC-S 2020), 2019.07.</p>
          <p>[c7] 한재혁, 권양섭, "디지털 증거 인증 및 디지털 포렌식 도구 검증제도에 관한 연구", 한국법과학회 2019 추계학술대회, 2019.10.</p>
          <p>[j11] Yun, W., Han, J., & Lee, S. (2019). 5W1H based Information Expression Standard for efficient digital forensic investigation. Journal of Digital Forensics, 13(2), 127-136.</p>          
          <p>[c6] 이선호, 한재혁, 이상진, "윈도우 실행파일의 특징 추출을 통한 프로파일링 기법 연구", 한국정보보호학회 하계학술대회(CISC-S 2019), 2019.06.</p>
          <p>[j10] Joun, J., Han, J., Jung, D., & Lee, S. (2018). Study on History Tracking Technique of the Document File through RSID Analysis in MS Word. Journal of the Korea Institute of Information Security & Cryptology, 28(6), 1439-1448.</p>
          <p>[j9] Kim, S., Han, J., & Lee, S. (2018). A Study on Detecting Data Hiding Area of Removable Storage Device Based on Flash Memory. Journal of Digital Forensics, 12(2), 21-29.</p>
          <p>[j8] Jung, B., Han, J., Choi, H., & Lee, S. (2018). A Study on the Possibility of Recover ing Deleted Data through Analysis of SQLite Journal in Messenger Application. Journal of Digital Forensics, 12(2), 11-20.</p>
          <p>[j7] Kim, J., Han, J., Choi, J. H., & Lee, S. (2018). The Method of Recovery for Deleted Record of Realm Database. Journal of the Korea Institute of Information Security & Cryptology, 28(3), 625-633.</p>
          <p>[c5] 김소희, 한재혁, 이상진, "USB 보안영역 탐지 방법에 대한 연구", 한국디지털포렌식학회 하계학술대회(WDFS-2018s), 2018.06.</p>
          <p>[c4] 정병찬, 한재혁, 최호용, 이상진, "메신저앱에서 메시지 삭제 방법에 따른 데이터 잔존 여부 및 복구가능성 연구", 한국디지털포렌식학회 하계학술대회(WDFS-2018s), 2018.06.</p>
          <p>[j6] Son, G., Han, J., & Lee, S. (2017). A Study of Method to Restore Deduplicated Files in Windows Server 2012. Journal of the Korea Institute of Information Security & Cryptology, 27(6), 1373-1383.</p>
          <p>[j5] Jung, B., Han, J., & Lee, S. J. (2017). A method of recovery for damaged ZIP files. Journal of the Korea Institute of Information Security & Cryptology, 27(5), 1107-1115.</p>
          <p>[j4] Han, J., & Lee, S. (2017). Fake GPS Detection for the Online Game Service on Server-Side. Journal of the Korea Institute of Information Security & Cryptology, 27(5), 1069-1076.</p>
          <p>[b1] 김민식, 이상진, <b>한재혁</b>, "디지털 포렌식 분석을 위한 EnScript 프로그래밍: 8가지 실전 예제로 배우는 EnScript 기초 및 활용 (ISBN: 9791186697382)", 비제이퍼블릭(BJ퍼블릭), 2017.07.</p>
          <p>[c3] 이승주, 한재혁, 이상진, "윈도우즈 텔레메트리 로그파일 분석 및 레지스트리 정보와 비교", 한국디지털포렌식학회 하계학술대회(WDFS-2017s), 2017.07.</p>
          <p>[c2] 김준기, 한재혁, 이상진,"로그인 정보 분석을 통합 웹 브라우저 포렌식 개선 방안", 한국정보보호학회 하계학술대회(CISC-S’16), 2017.06.22.</p>
          <p>[j3] Lee, J. H., Han, J., Lee, M. W., Choi, J. M., Baek, H., & Lee, S. J. (2017). A study on API wrapping in Themida and unpacking technique. Journal of the Korea Institute of Information Security & Cryptology, 27(1), 67-77.</p>
          <p>[j2] Jang, J., Bang, S. G., Han, J., & Lee, S. J. (2017). A Recovery Technique of PDF File in the Unit of Page. KIPS Transactions on Computer and Communication Systems, 6(1), 25-30.</p>
          <p>[c1] 정병준, 한재혁, 이상진, "ZIP 파일 복구 도구의 성능한계와 개선방안", 한국디지털포렌식학회 하계학술대회(WDFS-2016s), 2016.12.</p>
          <p>[j1] Kim, E., Jeon, S., Han, J., Lee, M., & Lee, S. (2015). An effective detection method for hiding data in compound-document files. Journal of the Korea Institute of Information Security & Cryptology, 25(6), 1485-1494.</p>
          
# - title: A Little More About Me
#   layout: text
#    content: | # this will include new lines to allow paragraphs
#      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
#
#      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: false #true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
